name = "one-million-checkboxes-api"
main = "src/index.js"
compatibility_date = "2025-07-18"

[[durable_objects.bindings]]
name = "CHECKBOX_ROOM"
class_name = "CheckboxRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CheckboxRoom"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
